version: "win#{build}"

# Should have VS2010 Express installed
os: Visual Studio 2015

init:
  - git config --global core.autocrlf input
  - cmake --version
  - msbuild /version

shallow_clone: true

clone_folder: c:\projects\flatcc

configuration:
  - Debug
  - Release

environment:
  matrix:
    - generator: "Visual Studio 12 2013"
    - generator: "Visual Studio 10 2010"
    - generator: "Visual Studio 14 2015"
    - generator: "Visual Studio 14 2015 Win64"

skip_tags: true

before_build:
  - echo Running cmake...
  - cd c:\projects\flatcc
  - mkdir build\MSVC
  - cd build\MSVC
  - cmake -G "%generator%" -DCMAKE_BUILD_TYPE=%configuration% ..\..

build:
  project: c:\projects\flatcc\build\MSVC\FlatCC.sln

test_script:
  - ctest -C "%configuration%" -VV

matrix:
  fast_finish: true
